name: Origami Lab core

on:
  push:
    branches:
      - main
      - "origami-lab/**"
  pull_request:
    paths:
      - "packages/core/**"
      - ".github/workflows/core.yml"

jobs:
  core-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/core
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Build and test
        run: npm test
